// mart-front-vue2/src/components/layout/index.vue
<template>
  <div class="wraper">
    <Header></Header>
    <div class="content">
      <slot></slot>
    </div>
    <Footer></Footer>
  </div>
</template>

<script>
import Header from "./header";
import Footer from "./footer";
import { defineComponent } from "vue";

export default defineComponent({
  name: "Layout",
  components: {
    Header,
    Footer,
  },
});
</script>

<style>
@import url("../../assets/css/reset.css");
@import url("../../assets/css/common.css");
@import url("../../assets/css/style.css");
</style>

// mart-manage-dva/src/components/layout/index.jsx
/*
 * @Author: heinan 
 * @Date: 2019-12-06 13:38:44 
 * @Last Modified by:   heinan 
 * @Last Modified time: 2019-12-06 13:38:44 
 */
import React, { Component } from 'react'

import "@/assets/css/bootstrap.min.css";
import "@/assets/css/iconfont.css";
import "@/assets/css/reset.css";
import "@/assets/css/common.css";
import "@/assets/css/style.css";

class Layout extends Component {
    render() {
        return (
            <div className="wraper">
                <header className="header">12313</header>
                <section>{this.props.children}</section>
            </div>
        )
    }
}
export default Layout;
